# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-28 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
