# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft_app', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('be1', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='be1', to='draft_app.Player')),
                ('be2', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='be2', to='draft_app.Player')),
                ('be3', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='be3', to='draft_app.Player')),
                ('be4', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='be4', to='draft_app.Player')),
                ('be5', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='be5', to='draft_app.Player')),
                ('be6', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='be6', to='draft_app.Player')),
                ('be7', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='be7', to='draft_app.Player')),
                ('dst', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='dst', to='draft_app.Player')),
                ('flex', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='flex', to='draft_app.Player')),
                ('k', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='k', to='draft_app.Player')),
                ('qb', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='qb', to='draft_app.Player')),
                ('rb1', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rb1', to='draft_app.Player')),
                ('rb2', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='rb2', to='draft_app.Player')),
                ('te', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='te', to='draft_app.Player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='draft_app.User')),
                ('wr1', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wr1', to='draft_app.Player')),
                ('wr2', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='wr2', to='draft_app.Player')),
            ],
        ),
    ]
